title: koduohutus
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

nav:
  - name: "liiklusohutus"
    link: "/liiklusohutus"

minima:
  skin: auto
  social_links:
    - title: github
      icon: github
      url: "https://github.com/ohutus"

url: https://ohutus.github.io/koduohutus

author:
  name: ohutus(valeNimi4, rohelibian)
